---
id: model
name: Model
full: Forms replacement incubator project
description: An unfinished replacement for horde/forms from the H4 incubator CVS.
list: horde
type: library
homepage: http://www.horde.org/libraries/model
authors:
  -
    name: Horde LLC
    user: tbd
    email: dev@horde.org
    role: lead
    active: true
version:
  release: 1.0.0alpha1
  api: 1.0.0
state:
  release: alpha
  api: alpha
license:
  identifier: LGP-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
  optional:
    composer:
      horde/test: ^3
